//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Selenium.Kendo {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Scripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Scripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Selenium.Kendo.Scripts", typeof(Scripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var a=$(arguments[0]).data(&apos;kendoCalendar&apos;).options.animation; var duration = 0; if(a) duration = a.horizontal.duration;} return duration;.
        /// </summary>
        internal static string Calendar_options_animation_horizontal_duration {
            get {
                return ResourceManager.GetString("Calendar_options_animation_horizontal_duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var a=$(arguments[0]).data(&apos;kendoCalendar&apos;).options.animation; var duration = 0;if(a) {return duration  = a.vertical.duration;} return duration;.
        /// </summary>
        internal static string Calendar_options_animation_vertical_duration {
            get {
                return ResourceManager.GetString("Calendar_options_animation_vertical_duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return $(arguments[0]).data(&apos;kendoCalendar&apos;).view().name;.
        /// </summary>
        internal static string Calendar_view_name {
            get {
                return ResourceManager.GetString("Calendar_view_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return JSON.stringify($(arguments[0]).data(&apos;kendoComboBox&apos;).dataSource.data());.
        /// </summary>
        internal static string ComboBox_datasource_data {
            get {
                return ResourceManager.GetString("ComboBox_datasource_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return $(arguments[0]).data(&apos;kendoComboBox&apos;).options.dataTextField;.
        /// </summary>
        internal static string ComboBox_options_dataTextField {
            get {
                return ResourceManager.GetString("ComboBox_options_dataTextField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return $(arguments[0]).data(&apos;kendoComboBox&apos;).options.dataValueField;.
        /// </summary>
        internal static string ComboBox_options_dataValueField {
            get {
                return ResourceManager.GetString("ComboBox_options_dataValueField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return $(arguments[0]).data(&apos;kendoDatePicker&apos;).close();.
        /// </summary>
        internal static string DatePicker_close {
            get {
                return ResourceManager.GetString("DatePicker_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return $(arguments[0]).data(&apos;kendoDatePicker&apos;).dateView.div;.
        /// </summary>
        internal static string DatePicker_dateView_div {
            get {
                return ResourceManager.GetString("DatePicker_dateView_div", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return $(arguments[0]).data(&apos;kendoDatePicker&apos;).dateView.popup.visible();.
        /// </summary>
        internal static string DatePicker_dateView_popup_visible {
            get {
                return ResourceManager.GetString("DatePicker_dateView_popup_visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return $(arguments[0]).data(&apos;kendoDatePicker&apos;).max().getTime();.
        /// </summary>
        internal static string DatePicker_max_get {
            get {
                return ResourceManager.GetString("DatePicker_max_get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $(arguments[0]).data(&apos;kendoDatePicker&apos;).max(arguments[1]);.
        /// </summary>
        internal static string DatePicker_max_set {
            get {
                return ResourceManager.GetString("DatePicker_max_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return $(arguments[0]).data(&apos;kendoDatePicker&apos;).min().getTime();.
        /// </summary>
        internal static string DatePicker_min_get {
            get {
                return ResourceManager.GetString("DatePicker_min_get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $(arguments[0]).data(&apos;kendoDatePicker&apos;).min(arguments[1]);.
        /// </summary>
        internal static string DatePicker_min_set {
            get {
                return ResourceManager.GetString("DatePicker_min_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return $(arguments[0]).data(&apos;kendoDatePicker&apos;).open();.
        /// </summary>
        internal static string DatePicker_open {
            get {
                return ResourceManager.GetString("DatePicker_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return $(arguments[0]).data(&apos;kendoDatePicker&apos;).options.depth;.
        /// </summary>
        internal static string DatePicker_options_depth {
            get {
                return ResourceManager.GetString("DatePicker_options_depth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return $(arguments[0]).data(&apos;kendoDatePicker&apos;).options.footer;.
        /// </summary>
        internal static string DatePicker_options_footer {
            get {
                return ResourceManager.GetString("DatePicker_options_footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return $(arguments[0]).data(&apos;kendoDatePicker&apos;).options.format;.
        /// </summary>
        internal static string DatePicker_options_format {
            get {
                return ResourceManager.GetString("DatePicker_options_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return $(arguments[0]).data(&apos;kendoDatePicker&apos;).options.prefix;.
        /// </summary>
        internal static string DatePicker_options_prefix {
            get {
                return ResourceManager.GetString("DatePicker_options_prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return $(arguments[0]).data(&apos;kendoDatePicker&apos;).options.start;.
        /// </summary>
        internal static string DatePicker_options_start {
            get {
                return ResourceManager.GetString("DatePicker_options_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return $(arguments[0]).data(&apos;kendoDatePicker&apos;).value().getTime();.
        /// </summary>
        internal static string DatePicker_value_get {
            get {
                return ResourceManager.GetString("DatePicker_value_get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return JSON.stringify($(arguments[0]).data(&apos;kendoDropDownList&apos;).dataSource.data());.
        /// </summary>
        internal static string DropDownList_datasource_data {
            get {
                return ResourceManager.GetString("DropDownList_datasource_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return $(arguments[0]).data(&apos;kendoDropDownList&apos;).options.dataTextField;.
        /// </summary>
        internal static string DropDownList_options_dataTextField {
            get {
                return ResourceManager.GetString("DropDownList_options_dataTextField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return $(arguments[0]).data(&apos;kendoDropDownList&apos;).options.dataValueField;.
        /// </summary>
        internal static string DropDownList_options_dataValueField {
            get {
                return ResourceManager.GetString("DropDownList_options_dataValueField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $(arguments[0]).data(&apos;kendoGrid&apos;).clearSelection();.
        /// </summary>
        internal static string Grid_clearSelection {
            get {
                return ResourceManager.GetString("Grid_clearSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var grid=$(arguments[0]).data(&apos;kendoGrid&apos;);var row=grid.tbody.find(&apos;&gt;tr:not(.k-grouping-row)&apos;).eq(arguments[1]);grid.select(row);.
        /// </summary>
        internal static string Grid_select_row {
            get {
                return ResourceManager.GetString("Grid_select_row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $(arguments[0]).data(&apos;kendoSlider&apos;).disable();.
        /// </summary>
        internal static string Slider_disable {
            get {
                return ResourceManager.GetString("Slider_disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $(arguments[0]).data(&apos;kendoSlider&apos;).enable();.
        /// </summary>
        internal static string Slider_enable {
            get {
                return ResourceManager.GetString("Slider_enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return $(arguments[0]).data(&apos;kendoSlider&apos;).options.largeStep;.
        /// </summary>
        internal static string Slider_options_largeStep_get {
            get {
                return ResourceManager.GetString("Slider_options_largeStep_get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return $(arguments[0]).data(&apos;kendoSlider&apos;).options.max;.
        /// </summary>
        internal static string Slider_options_max_get {
            get {
                return ResourceManager.GetString("Slider_options_max_get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return $(arguments[0]).data(&apos;kendoSlider&apos;).options.min;.
        /// </summary>
        internal static string Slider_options_min_get {
            get {
                return ResourceManager.GetString("Slider_options_min_get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return $(arguments[0]).data(&apos;kendoSlider&apos;).options.showButtons;.
        /// </summary>
        internal static string Slider_options_showButtons_get {
            get {
                return ResourceManager.GetString("Slider_options_showButtons_get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return $(arguments[0]).data(&apos;kendoSlider&apos;).options.smallStep;.
        /// </summary>
        internal static string Slider_options_smallStep_get {
            get {
                return ResourceManager.GetString("Slider_options_smallStep_get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return $(arguments[0]).data(&apos;kendoSlider&apos;).value();.
        /// </summary>
        internal static string Slider_value_get {
            get {
                return ResourceManager.GetString("Slider_value_get", resourceCulture);
            }
        }
    }
}
